config/routes.rb
BaseClinic::Application.routes.draw do
  resources :patients

  post 'pitch_signup' => 'pages#pitch_signup'
  root 'pages#pitch'

  

end

app/models/patient.rb
class Patient < ActiveRecord::Base

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/pitch_user.rb
class PitchUser < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def pitch
    render :pitch, :layout => 'base'
  end

  def pitch_signup
    PitchUser.create(params.require(:user).permit(:email))
    head 200
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  def index
    @patients = Patient.all
  end

  # GET /patients/1
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  def create
    @patient = Patient.new(patient_params)

    if @patient.save
      redirect_to @patient, notice: 'Patient was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /patients/1
  def update
    if @patient.update(patient_params)
      redirect_to @patient, notice: 'Patient was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /patients/1
  def destroy
    @patient.destroy
    redirect_to patients_url, notice: 'Patient was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def patient_params
      params.require(:patient).permit(:handle, :password, :first_name, :last_name, :email_address, :phone_number, :credentials, :license_number, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_flash
  end
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "BaseClinic"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'


  %body
    .navbar
      .container
        %a.navbar-brand{:href => "#"} BaseClinic
        %ul.pull-right.navbar-text.list-inline
          %li
            %a(href="#")
              %i.icon-search
              Search
          %li
            %a(href="#")
              %i.icon-question-sign
              Need Help?
          %li
            %a(href="#")
              Travis Topham (HIS)
              %i.icon-caret-down

    .container.full-height
      .row.full-height
        .col-2.sidebar-col
          = render 'shared/sidebar'
        .col-10.main.full-height
          = bootstrap_flash
          = yield

      %footer
        %p &copy; Company 2013
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/layouts/base.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "BaseClinic"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'


  %body
    = yield
    = javascript_include_tag "application"

app/views/pages/pitch.html.haml
.hero
  %h1.title
    BaseClinic
  %h3.coming-soon
    Coming early 2014.
  %h2.sub-title
    A whole new way to manage your hearing center.
  .content
    BaseClinic is a web-based software on a crusade - to help hearing
    %br
    professionals run a more efficient, productive, and modern practice.

.email
  %p
    Enter your email and get exclusive research on hearing
    %br
    industries best practices before the software is out.
  %p
    = form_tag(pitch_signup_path) do
      = email_field_tag 'user[email]', '', :class => 'email-address'
      = submit_tag "Keep me posted!", :class => 'btn btn-primary'

.container
  .stories.row

    .col-offset-2.col-4.story
      .title
        We were hearing specialists too
      .content
        %p In 2012 my brother Travis and I (Skylar) were working as Hearing Specialists for a large hearing aid company. I was running two clinics in the L.A., Travis was over three clinics throughout Milwaukee.
        %p Things were going well. Our clinics were growing, revenue was climbing and most importantly, our patients were happy.
        %p Just one little problem, we felt like things could be running a little smoother on the business side of things.
    .col-4.story
      .title
        Figuring out the fix
      .content
        %p We spent a lot of time thinking about how we could run our clinics better. What did Ineed to know? How often? What kind of things? From who? Could other people in the company find this information useful too? And so on.
        %p Travis started creating spreadsheets that XXXX. I on the other hand was patching together bits and pieces of other software applications to XXX
        %p We started to discover there was a better way. We just needed to build it.
    .col-offset-2.col-4.story
      .title
        We craved organization
      .content
        %p We're both sorta OCD when it comes to organization, and the ‘organizational’ software we were required to use didn't seem to fit the bill. We certainly didn’t need another business intelligence dashboard full of stats and graphs.
        %p What we had was an organizational problem.
    .col-4.story
      .title
        Building it
      .content
        %p We pulled together an amazing team, and started making things happen. We prototyped, and prototyped, and prototyped some more until we absolutely nailed it. From a huge pile of possibilities we made a simple, useful software that solved real problems. It's a product worthy of being used.

.love-it
  .title You'll use it because you love it
  .content
    We don’t want you to use BaseClinic because it’s the best out of a bunch of bad options. We want
    %br
    you to use BaseClinic because you absolutely love it.

.container.footer
  .row
    .col-offset-2.col-4.press
      .title
        Press Room
      .content
        If you find what we're doing worth writing
        about, we'd love to chat.
        %ul
          %li If you are looking to be one of the first to review BaseClinic, you can contact us a press@baseclinic.com
          %li For up to date news, check out our blog or Facebook page.

    .col-4.contact
      .title
        Contact
      .content
      %p We’d love to hear from you!
      %p Business owners, hearing professionals, future friends in the Industry, etc. Interested in helping spread the BaseClinic word? We'd love to hear from you! Have other partnership opportunities or ideas? Don't hesitate to reach out!
      %p
        %a hi@baseclinic.com

.modal.fade.hide
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
        %h4.modal-title Got it!
      .modal-body
        %p Keep your eyes peeled for something in your inbox.
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close

app/views/patients/_form.html.haml
= form_for @patient do |f|
  - if @patient.errors.any?
    #error_explanation
      %h2= "#{pluralize(@patient.errors.count, "error")} prohibited this patient from being saved:"
      %ul
        - @patient.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :password
    = f.text_field :password
  .field
    = f.label :first_name
    = f.text_field :first_name
  .field
    = f.label :last_name
    = f.text_field :last_name
  .field
    = f.label :email_address
    = f.text_field :email_address
  .field
    = f.label :phone_number
    = f.text_field :phone_number
  .field
    = f.label :credentials
    = f.text_field :credentials
  .field
    = f.label :license_number
    = f.text_field :license_number
  .field
    = f.label :avatar
    = f.text_field :avatar
  .actions
    = f.submit 'Save'

app/views/patients/edit.html.haml
%h1 Editing patient

= render 'form'

= link_to 'Show', @patient
\|
= link_to 'Back', patients_path

app/views/patients/index.html.haml
%h1 Listing patients

%table
  %tr
    %th Handle
    %th Password
    %th First name
    %th Last name
    %th Email address
    %th Phone number
    %th Credentials
    %th License number
    %th Avatar
    %th
    %th
    %th

  - @patients.each do |patient|
    %tr
      %td= patient.handle
      %td= patient.password
      %td= patient.first_name
      %td= patient.last_name
      %td= patient.email_address
      %td= patient.phone_number
      %td= patient.credentials
      %td= patient.license_number
      %td= patient.avatar
      %td= link_to 'Show', patient
      %td= link_to 'Edit', edit_patient_path(patient)
      %td= link_to 'Destroy', patient, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Patient', new_patient_path

app/views/patients/new.html.haml
%h1 New patient

= render 'form'

= link_to 'Back', patients_path

app/views/patients/show.html.haml
- if notice
  %p#notice= notice

.row.full-height
  .col-9
    %h3= "Patients / #{@patient.full_name}"

    .btn-group
      %button.btn.btn-default.active Notes
      %button.btn.btn-default Test Results
      %button.btn.btn-default Transaction History
      %button.btn.btn-default Progress

  .col-3.rail.flatten
    %section.appointment
      %button.btn.btn-default.full-width Start a new appointment
      .text-center
        %i.icon-user.user
      .full-name= @patient.full_name
      .email-address= @patient.email_address
      .phone-number= @patient.phone_number

      %a.pull-left(href="#")
        Show details
        %i.icon-caret-down
      = link_to 'Update details', edit_patient_path(@patient), :class => 'pull-right'
      .clearfix

    %section.tasks.curved-border
      .header
        .pull-left
          %i.icon-check
          Tasks
        .pull-right
          %a(href='#') + Add a task
        .clearfix
      Today
      %table
        %tr
          %td
            %input(type="checkbox")
          %td Hearing aids
        %tr
          %td
            %input(type="checkbox")
          %td Find out the doctors information that Pt will be seeing. Good networking opportunity. (Re: Note)
      %a(href="#") Completed Tasks (4)

    %section.documents.curved-border
      .header
        .pull-left
          %i.icon-file
          Documents
        .pull-right
          %a(href='#') + Add a doc
        .clearfix
      %ul.list-unstyled
        %li
          %a(href="#")
            %i.icon-pencil
            Intake forms (2)
        %li
          %a(href="#")
            %i.icon-pencil
            Waivers (3)
        %li
          %a(href="#")
            %i.icon-volume-up
            Audiograms (1)
        %li
          %a(href="#")
            %i.icon-dollar
            Purchase Agreements (1)
        %li
          %a(href="#")
            %i.icon-check
            Delivery Checklist (1)
        %li
          %a(href="#")
            %i.icon-calendar
            SOAP appt summaries (13)
        %li
          %a(href="#")
            %i.icon-pencil
            All notes (47)
        %li
          %a(href="#")
            %i.icon-wrench
            Repair forms (6)
        %li
          %a(href="#")
            %i.icon-pencil
            Return for credit (0)

app/views/shared/_sidebar.html.haml
.sidebar-nav
  %ul.nav.nav-list
    %li.nav-header Your Practice
    %li
      = link_to(root_path) do
        %i.icon-home
        Dashboard
    %li
      %a(href="/")
        %i.icon-building
        Clinics (0)
    %li
      = link_to(patients_path) do
        %i.icon-user
        Patients (0)
    %li
      %a(href="/")
        %i.icon-calendar
        Schedule (0)
    %li
      %a(href="/")
        %i.icon-check
        Tasks (0)
  %ul.nav.nav-list
    %li.nav-header Your Reports
    %li
      %a(href="/")
        %i.icon-dollar
        Sales
    %li
      %a(href="/")
        %i.icon-calendar-empty
        Appointments
  %ul.nav.nav-list
    %li.nav-header Configuration
    %li
      %a(href="/")
        %i.icon-gear
        Settings

app/views/shared/modal.html.haml
.modal.fade
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
        %h4.modal-title Modal title
      .modal-body
        %p One fine body…
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close
        %button.btn.btn-primary{:type => "button"} Save changes